[Interface]
Address = 172.16.100.1
PrivateKey = <AWS_PRIVATE_KEY>
ListenPort = 60031

# Azure Spoke
[Peer]
PublicKey = <AZURE_PUBLIC_KEY>
Endpoint = <AZURE_PUBLIC_IP>:60031
AllowedIPs = 10.1.0.0/16, 172.16.100.2/32
PersistentKeepalive = 25

# On-Premises Spoke
[Peer]
PublicKey = <ON_PREMISES_PUBLIC_KEY>
Endpoint = <ON_PREMISES_PUBLIC_IP>:60032
AllowedIPs = 10.2.0.0/16, 172.16.100.3/32
PersistentKeepalive = 25