[Interface]
Address = 172.168.100.1/24
PrivateKey = *HIDDEN*
ListenPort = 51820

[Peer]
PublicKey = Qtiw5PTYlzMgGnVcbEaIZo9Er1ppl6zun+MihNWRtlA=
Endpoint = 20.119.50.200:51820
AllowedIPs = 10.1.0.0/16,172.168.100.2/32
PersistentKeepalive = 25