[Interface]
Address = 172.16.100.2
PrivateKey = <AZURE_PRIVATE_KEY>
ListenPort = 60031

[Peer]
PublicKey = <AWS_PUBLIC_KEY>
Endpoint = <AWS_PUBLIC_IP>:60031

AllowedIPs = 10.0.0.0/16,10.2.0.0/16,172.16.100.1/32,172.16.100.3/32

PersistentKeepalive = 25